source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'GoogleMaps'
pod 'AFNetworking', '~> 3.0'
pod 'UIActionSheet+Blocks'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'UIAlertView+Blocks'
pod 'ARSlidingPanel'

